-- 补充央企国企 (2026-06-07)
-- 中国烟草总公司
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国烟草总公司', '全国', '["热招中","可转正"]', '2027届/2028届', '烟草工程/机械/电气/财务/市场营销/信息技术', '全球最大烟草企业，央企，待遇优厚。招聘管理培训生、技术研发、市场营销等岗位', 'http://www.tobacco.gov.cn', 'tobacco.gov.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '国家开发银行', '北京/全国', '["热招中","可转正"]', '2027届/2028届', '金融/经济/法律/风险管理/信息技术', '政策性银行，直属国务院，央企。暑期实习及校招，招聘信贷、风险管理、研究分析等岗位', 'https://www.cdb.com.cn', 'www.cdb.com.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国进出口银行', '北京/全国', '["热招中"]', '2027届/2028届', '金融/国际贸易/法律/风险管理/财务会计', '政策性银行，支持进出口贸易和对外投资。招聘信贷业务、国际结算、风险管理等岗位', 'https://www.eximbank.gov.cn', 'www.eximbank.gov.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国农业发展银行', '北京/全国', '["热招中"]', '2027届/2028届', '金融/农业经济/法律/信息技术/财务会计', '政策性银行，服务三农。招聘信贷管理、风险管理、信息技术等岗位', 'https://www.adbc.com.cn', 'www.adbc.com.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国保利集团', '北京/广州/上海', '["热招中"]', '2027届/2028届', '国际贸易/房地产/文化艺术/财务/信息技术', '央企，业务涵盖国际贸易、房地产开发、文化艺术经营等。总部北京', 'https://www.poly.com.cn', 'www.poly.com.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国铁路通信信号集团', '北京/全国', '["热招中"]', '2027届/2028届', '通信工程/信号控制/电气工程/计算机/自动化', '央企，全球最大轨道交通控制系统提供商。中国通号，招聘研发、工程、技术等岗位', 'https://www.crsc.cn', 'www.crsc.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国铁塔股份有限公司', '北京/全国', '["热招中"]', '2027届/2028届', '通信/电气/计算机/土木工程/财务', '全球最大通信铁塔基础设施服务商，由中国移动、联通、电信联合设立', 'https://www.china-tower.com', 'www.china-tower.com', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国航空油料集团', '北京/全国', '["热招中"]', '2027届/2028届', '石油化工/物流管理/机械/安全工程/财务', '央企，亚洲最大航油供应企业。中国航油，招聘航油储运、安全管理等岗位', 'https://www.cnaf.com', 'www.cnaf.com', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国电气装备集团', '上海/西安/济南', '["热招中","可转正"]', '2027届/2028届', '电气工程/电力系统/机械/自动化/新能源', '央企，由中国西电、许继、平高、山东电工等重组而成，电力装备龙头', 'https://www.ceec.net.cn', 'www.ceec.net.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '南水北调集团', '北京/中线/东线', '["热招中"]', '2027届/2028届', '水利工程/土木工程/环境工程/机械/电气', '央企，负责南水北调工程建设运营。招聘水利、土木、环境等专业人才', 'https://www.nsbd.cn', 'www.nsbd.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国国新控股', '北京', '["热招中"]', '2027届/2028届', '金融/投资/财务/法律/信息技术', '央企，国有资本运营公司。招聘投资分析、基金管理、风险管理等岗位', 'https://www.crhc.cn', 'www.crhc.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国诚通控股集团', '北京', '["热招中"]', '2027届/2028届', '金融/物流/资产管理/人力资源/信息技术', '央企，国有资本运营公司试点。招聘资产管理、资本运营、物流管理等岗位', 'https://www.cctgroup.com.cn', 'www.cctgroup.com.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国广电网络集团', '北京/全国', '["热招中"]', '2027届/2028届', '通信/网络工程/新媒体/计算机/市场营销', '央企，全国有线电视网络整合主体，第四大通信运营商。5G+广电网络', 'https://www.chinabroadcasting.cn', 'www.chinabroadcasting.cn', datetime('now'), datetime('now'));
INSERT INTO companies (row_num, company_name, locations, tags_json, target_audience, job_positions, description, website_url, website_text, created_at, updated_at) VALUES ((SELECT MAX(row_num)+1 FROM companies), '中国铁路物资集团', '北京/全国', '["热招中"]', '2027届/2028届', '物流管理/铁路工程/供应链/机械/财务', '央企，中国铁路物资供应核心企业。招聘供应链管理、物流规划等岗位', 'https://www.crmsc.com.cn', 'www.crmsc.com.cn', datetime('now'), datetime('now'));
-- (中国冶金地质总局 已存在，跳过)
