-- Fix company names for rows 1525-1585
UPDATE companies SET company_name = '中国航空油料集团', locations = '北京' WHERE row_num = 1525;
UPDATE companies SET company_name = '中国民航信息集团', locations = '北京' WHERE row_num = 1526;
UPDATE companies SET company_name = '中国铁路通信信号集团', locations = '北京' WHERE row_num = 1527;
UPDATE companies SET company_name = '中国铁道建筑集团', locations = '北京' WHERE row_num = 1528;
UPDATE companies SET company_name = '中国交通建设集团', locations = '北京' WHERE row_num = 1529;
UPDATE companies SET company_name = '中国国际工程咨询公司', locations = '北京' WHERE row_num = 1530;
UPDATE companies SET company_name = '中国煤炭科工集团', locations = '北京' WHERE row_num = 1531;
UPDATE companies SET company_name = '中国钢研科技集团', locations = '北京' WHERE row_num = 1532;
UPDATE companies SET company_name = '中国有色矿业集团', locations = '北京' WHERE row_num = 1533;
UPDATE companies SET company_name = '有研科技集团', locations = '北京' WHERE row_num = 1534;
UPDATE companies SET company_name = '矿冶科技集团', locations = '北京' WHERE row_num = 1535;
UPDATE companies SET company_name = '中国国际技术智力合作集团', locations = '北京' WHERE row_num = 1536;
UPDATE companies SET company_name = '中国建设科技集团', locations = '北京' WHERE row_num = 1537;
UPDATE companies SET company_name = '中国保利集团', locations = '北京' WHERE row_num = 1538;
UPDATE companies SET company_name = '中国华侨城集团', locations = '深圳' WHERE row_num = 1539;
UPDATE companies SET company_name = '中国国新控股', locations = '北京' WHERE row_num = 1540;
UPDATE companies SET company_name = '中国铁塔', locations = '北京' WHERE row_num = 1541;
UPDATE companies SET company_name = '中国广播电视网络集团', locations = '北京' WHERE row_num = 1542;
UPDATE companies SET company_name = '中国南水北调集团', locations = '北京' WHERE row_num = 1543;
UPDATE companies SET company_name = '中国矿产资源集团', locations = '雄安' WHERE row_num = 1544;
UPDATE companies SET company_name = '中国融通文化教育集团', locations = '北京' WHERE row_num = 1545;
UPDATE companies SET company_name = '广州港集团', locations = '广州' WHERE row_num = 1546;
UPDATE companies SET company_name = '深圳国际控股', locations = '深圳' WHERE row_num = 1547;
UPDATE companies SET company_name = '广东省广新控股集团', locations = '广州' WHERE row_num = 1548;
UPDATE companies SET company_name = '广东省交通集团', locations = '广州' WHERE row_num = 1549;
UPDATE companies SET company_name = '广东粤海控股', locations = '广州/香港' WHERE row_num = 1550;
UPDATE companies SET company_name = '广州发展集团', locations = '广州' WHERE row_num = 1551;
UPDATE companies SET company_name = '广州市建筑集团', locations = '广州' WHERE row_num = 1552;
UPDATE companies SET company_name = '厦门港务控股', locations = '厦门' WHERE row_num = 1553;
UPDATE companies SET company_name = '漳州片仔癀药业', locations = '漳州' WHERE row_num = 1554;
UPDATE companies SET company_name = '柳工集团', locations = '柳州' WHERE row_num = 1555;
UPDATE companies SET company_name = '玉柴集团', locations = '玉林' WHERE row_num = 1556;
UPDATE companies SET company_name = '海南省发展控股', locations = '海口' WHERE row_num = 1557;
UPDATE companies SET company_name = '陕西省地方电力集团', locations = '西安' WHERE row_num = 1558;
UPDATE companies SET company_name = '甘肃公航旅集团', locations = '兰州' WHERE row_num = 1559;
UPDATE companies SET company_name = '贵州磷化集团', locations = '贵阳' WHERE row_num = 1560;
UPDATE companies SET company_name = '腾讯音乐 Tencent Music', locations = '深圳' WHERE row_num = 1561;
UPDATE companies SET company_name = '网易云音乐 NetEase Cloud Music', locations = '杭州' WHERE row_num = 1562;
UPDATE companies SET company_name = '快看漫画 Kuaikan', locations = '北京' WHERE row_num = 1563;
UPDATE companies SET company_name = '得物 Poizon', locations = '上海' WHERE row_num = 1564;
UPDATE companies SET company_name = 'SHEIN', locations = '广州/南京' WHERE row_num = 1565;
UPDATE companies SET company_name = 'Temu(拼多多国际)', locations = '上海' WHERE row_num = 1566;
UPDATE companies SET company_name = '传音控股 Transsion', locations = '深圳' WHERE row_num = 1567;
UPDATE companies SET company_name = '大华股份 Dahua Technology', locations = '杭州' WHERE row_num = 1568;
UPDATE companies SET company_name = '宇视科技 Uniview', locations = '杭州' WHERE row_num = 1569;
UPDATE companies SET company_name = '大族数控', locations = '深圳' WHERE row_num = 1570;
UPDATE companies SET company_name = '科沃斯 Ecovacs', locations = '苏州' WHERE row_num = 1571;
UPDATE companies SET company_name = '追觅科技 Dreame', locations = '苏州' WHERE row_num = 1572;
UPDATE companies SET company_name = '石头科技 Roborock', locations = '北京' WHERE row_num = 1573;
UPDATE companies SET company_name = '云鲸 Narwal', locations = '深圳' WHERE row_num = 1574;
UPDATE companies SET company_name = '影石 Insta360', locations = '深圳' WHERE row_num = 1575;
UPDATE companies SET company_name = '韶音 Shokz', locations = '深圳' WHERE row_num = 1576;
UPDATE companies SET company_name = '安克创新 Anker', locations = '长沙/深圳' WHERE row_num = 1577;
UPDATE companies SET company_name = '绿联科技 Ugreen', locations = '深圳' WHERE row_num = 1578;
UPDATE companies SET company_name = '倍思 Baseus', locations = '深圳' WHERE row_num = 1579;
UPDATE companies SET company_name = '品胜 Pisen', locations = '深圳' WHERE row_num = 1580;
UPDATE companies SET company_name = '漫步者 Edifier', locations = '东莞' WHERE row_num = 1581;
UPDATE companies SET company_name = '万兴科技 Wondershare', locations = '深圳' WHERE row_num = 1582;
UPDATE companies SET company_name = '高德软件 Amap', locations = '北京' WHERE row_num = 1583;
UPDATE companies SET company_name = '小马智行 Pony.ai', locations = '北京/广州' WHERE row_num = 1584;
UPDATE companies SET company_name = '文远知行 WeRide', locations = '广州' WHERE row_num = 1585;
