-- Remove /careers PATH only (keep domain-level careers.*)
-- 77 URLs fixed

UPDATE companies SET website_url = 'https://www.lixiang.com', website_text = 'lixiang.com' WHERE row_num = 40;
UPDATE companies SET website_url = 'https://www.catl.com', website_text = 'catl.com' WHERE row_num = 42;
UPDATE companies SET website_url = 'https://www.antgroup.com', website_text = 'antgroup.com' WHERE row_num = 100;
UPDATE companies SET website_url = 'https://www.unisoc.com', website_text = 'unisoc.com' WHERE row_num = 122;
UPDATE companies SET website_url = 'https://www.hesaitech.com', website_text = 'hesaitech.com' WHERE row_num = 125;
UPDATE companies SET website_url = 'https://www.leapmotor.com', website_text = 'leapmotor.com' WHERE row_num = 145;
UPDATE companies SET website_url = 'https://www.zeekr.com', website_text = 'zeekr.com' WHERE row_num = 146;
UPDATE companies SET website_url = 'https://www.moonton.com', website_text = 'moonton.com' WHERE row_num = 163;
UPDATE companies SET website_url = 'https://www.accenture.cn', website_text = 'accenture.cn' WHERE row_num = 196;
UPDATE companies SET website_url = 'https://www.united-imaging.com', website_text = 'united-imaging.com' WHERE row_num = 220;
UPDATE companies SET website_url = 'https://www.unitree.com', website_text = 'unitree.com' WHERE row_num = 284;
UPDATE companies SET website_url = 'https://www.landspace.com', website_text = 'landspace.com' WHERE row_num = 302;
UPDATE companies SET website_url = 'https://www.yuewen.com', website_text = 'yuewen.com' WHERE row_num = 320;
UPDATE companies SET website_url = 'https://www.sheingroup.com', website_text = 'sheingroup.com' WHERE row_num = 321;
UPDATE companies SET website_url = 'https://www.pony.ai', website_text = 'pony.ai' WHERE row_num = 328;
UPDATE companies SET website_url = 'https://www.zhongan.com', website_text = 'zhongan.com' WHERE row_num = 334;
UPDATE companies SET website_url = 'https://www.zhonglun.com', website_text = 'zhonglun.com' WHERE row_num = 342;
UPDATE companies SET website_url = 'https://www.genscript.com.cn', website_text = 'genscript.com.cn' WHERE row_num = 358;
UPDATE companies SET website_url = 'https://music.163.com', website_text = 'music.163.com' WHERE row_num = 371;
UPDATE companies SET website_url = 'https://www.ximalaya.com', website_text = 'ximalaya.com' WHERE row_num = 372;
UPDATE companies SET website_url = 'https://www.dingtalk.com', website_text = 'dingtalk.com' WHERE row_num = 434;
UPDATE companies SET website_url = 'https://www.ele.me', website_text = 'ele.me' WHERE row_num = 444;
UPDATE companies SET website_url = 'https://www.keep.com', website_text = 'keep.com' WHERE row_num = 487;
UPDATE companies SET website_url = 'https://www.futunn.com', website_text = 'futunn.com' WHERE row_num = 493;
UPDATE companies SET website_url = 'https://www.pharmaron.cn', website_text = 'pharmaron.cn' WHERE row_num = 520;
UPDATE companies SET website_url = 'https://www.tigermed.net', website_text = 'tigermed.net' WHERE row_num = 522;
UPDATE companies SET website_url = 'https://www.tongwei.com', website_text = 'tongwei.com' WHERE row_num = 534;
UPDATE companies SET website_url = 'https://www.4paradigm.com', website_text = '4paradigm.com' WHERE row_num = 569;
UPDATE companies SET website_url = 'https://www.pingcap.com', website_text = 'pingcap.com' WHERE row_num = 572;
UPDATE companies SET website_url = 'https://www.weride.ai', website_text = 'weride.ai' WHERE row_num = 577;
UPDATE companies SET website_url = 'https://www.luckincoffee.com', website_text = 'luckincoffee.com' WHERE row_num = 593;
UPDATE companies SET website_url = 'https://www.empyrean.com.cn', website_text = 'empyrean.com.cn' WHERE row_num = 595;
UPDATE companies SET website_url = 'https://www.didiglobal.com', website_text = 'didiglobal.com' WHERE row_num = 612;
UPDATE companies SET website_url = 'https://www.haidilao.com', website_text = 'haidilao.com' WHERE row_num = 647;
UPDATE companies SET website_url = 'https://www.bloomagebiotech.com', website_text = 'bloomagebiotech.com' WHERE row_num = 704;
UPDATE companies SET website_url = 'https://www.piesat.cn', website_text = 'piesat.cn' WHERE row_num = 728;
UPDATE companies SET website_url = 'https://www.feihe.com', website_text = 'feihe.com' WHERE row_num = 750;
UPDATE companies SET website_url = 'https://www.yuewen.com', website_text = 'yuewen.com' WHERE row_num = 769;
UPDATE companies SET website_url = 'https://www.oceanbase.com', website_text = 'oceanbase.com' WHERE row_num = 771;
UPDATE companies SET website_url = 'https://www.zilliz.com', website_text = 'zilliz.com' WHERE row_num = 775;
UPDATE companies SET website_url = 'https://www.dreame.com', website_text = 'dreame.com' WHERE row_num = 786;
UPDATE companies SET website_url = 'https://www.yadea.com.cn', website_text = 'yadea.com.cn' WHERE row_num = 791;
UPDATE companies SET website_url = 'https://www.tuya.com', website_text = 'tuya.com' WHERE row_num = 814;
UPDATE companies SET website_url = 'https://www.ecovacs.com', website_text = 'ecovacs.com' WHERE row_num = 817;
UPDATE companies SET website_url = 'https://www.roborock.com', website_text = 'roborock.com' WHERE row_num = 818;
UPDATE companies SET website_url = 'https://www.laiye.com', website_text = 'laiye.com' WHERE row_num = 819;
UPDATE companies SET website_url = 'https://www.innosilicon.com.cn', website_text = 'innosilicon.com.cn' WHERE row_num = 828;
UPDATE companies SET website_url = 'https://www.picoxr.com', website_text = 'picoxr.com' WHERE row_num = 838;
UPDATE companies SET website_url = 'https://www.empyrean.com.cn', website_text = 'empyrean.com.cn' WHERE row_num = 850;
UPDATE companies SET website_url = 'https://www.mgi-tech.com', website_text = 'mgi-tech.com' WHERE row_num = 853;
UPDATE companies SET website_url = 'https://www.qualcomm.cn', website_text = 'qualcomm.cn' WHERE row_num = 873;
UPDATE companies SET website_url = 'https://www.bosch.com.cn', website_text = 'bosch.com.cn' WHERE row_num = 876;
UPDATE companies SET website_url = 'https://www.astrazeneca.com.cn', website_text = 'astrazeneca.com.cn' WHERE row_num = 881;
UPDATE companies SET website_url = 'https://www.meitu.com', website_text = 'meitu.com' WHERE row_num = 910;
UPDATE companies SET website_url = 'https://www.smzdm.com', website_text = 'smzdm.com' WHERE row_num = 918;
UPDATE companies SET website_url = 'https://www.cctc.cc', website_text = 'cctc.cc' WHERE row_num = 952;
UPDATE companies SET website_url = 'https://www.hanslaser.com', website_text = 'hanslaser.com' WHERE row_num = 960;
UPDATE companies SET website_url = 'https://www.freshhema.com', website_text = 'freshhema.com' WHERE row_num = 976;
UPDATE companies SET website_url = 'https://www.pagoda.com.cn', website_text = 'pagoda.com.cn' WHERE row_num = 977;
UPDATE companies SET website_url = 'https://www.samsung.com.cn', website_text = 'samsung.com.cn' WHERE row_num = 1399;
UPDATE companies SET website_url = 'https://www.bosch.com.cn', website_text = 'bosch.com.cn' WHERE row_num = 1404;
UPDATE companies SET website_url = 'https://www.honeywell.com.cn', website_text = 'honeywell.com.cn' WHERE row_num = 1408;
UPDATE companies SET website_url = 'https://www.rtx.com', website_text = 'rtx.com' WHERE row_num = 1409;
UPDATE companies SET website_url = 'https://www.boeing.com', website_text = 'boeing.com' WHERE row_num = 1411;
UPDATE companies SET website_url = 'https://www.novartis.com.cn', website_text = 'novartis.com.cn' WHERE row_num = 1416;
UPDATE companies SET website_url = 'https://www.lilly.com.cn', website_text = 'lilly.com.cn' WHERE row_num = 1420;
UPDATE companies SET website_url = 'https://www.astrazeneca.com.cn', website_text = 'astrazeneca.com.cn' WHERE row_num = 1421;
UPDATE companies SET website_url = 'https://www.mondelezinternational.com', website_text = 'mondelezinternational.com' WHERE row_num = 1431;
UPDATE companies SET website_url = 'https://www.mcdonalds.com.cn', website_text = 'mcdonalds.com.cn' WHERE row_num = 1437;
UPDATE companies SET website_url = 'https://www.yumchina.com', website_text = 'yumchina.com' WHERE row_num = 1438;
UPDATE companies SET website_url = 'https://www.costco.com.cn', website_text = 'costco.com.cn' WHERE row_num = 1440;
UPDATE companies SET website_url = 'https://www.accenture.cn', website_text = 'accenture.cn' WHERE row_num = 1441;
UPDATE companies SET website_url = 'https://www.hsbc.com.cn', website_text = 'hsbc.com.cn' WHERE row_num = 1446;
UPDATE companies SET website_url = 'https://www.goldmansachs.com', website_text = 'goldmansachs.com' WHERE row_num = 1451;
UPDATE companies SET website_url = 'https://www.jpmorganchase.com', website_text = 'jpmorganchase.com' WHERE row_num = 1452;
UPDATE companies SET website_url = 'https://www.bain.com', website_text = 'bain.com' WHERE row_num = 1456;
UPDATE companies SET website_url = 'https://www.tesla.cn', website_text = 'tesla.cn' WHERE row_num = 1457;

-- Also fix apply_url with /careers path
-- 77 apply_url fixes

UPDATE companies SET apply_url = 'https://www.lixiang.com', apply_text = 'lixiang.com' WHERE row_num = 40 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.catl.com', apply_text = 'catl.com' WHERE row_num = 42 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.antgroup.com', apply_text = 'antgroup.com' WHERE row_num = 100 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.unisoc.com', apply_text = 'unisoc.com' WHERE row_num = 122 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.hesaitech.com', apply_text = 'hesaitech.com' WHERE row_num = 125 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.leapmotor.com', apply_text = 'leapmotor.com' WHERE row_num = 145 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.zeekr.com', apply_text = 'zeekr.com' WHERE row_num = 146 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.moonton.com', apply_text = 'moonton.com' WHERE row_num = 163 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.accenture.cn', apply_text = 'accenture.cn' WHERE row_num = 196 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.united-imaging.com', apply_text = 'united-imaging.com' WHERE row_num = 220 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.unitree.com', apply_text = 'unitree.com' WHERE row_num = 284 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.landspace.com', apply_text = 'landspace.com' WHERE row_num = 302 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.yuewen.com', apply_text = 'yuewen.com' WHERE row_num = 320 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.sheingroup.com', apply_text = 'sheingroup.com' WHERE row_num = 321 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.pony.ai', apply_text = 'pony.ai' WHERE row_num = 328 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.zhongan.com', apply_text = 'zhongan.com' WHERE row_num = 334 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.zhonglun.com', apply_text = 'zhonglun.com' WHERE row_num = 342 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.genscript.com.cn', apply_text = 'genscript.com.cn' WHERE row_num = 358 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://music.163.com', apply_text = 'music.163.com' WHERE row_num = 371 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.ximalaya.com', apply_text = 'ximalaya.com' WHERE row_num = 372 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.dingtalk.com', apply_text = 'dingtalk.com' WHERE row_num = 434 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.ele.me', apply_text = 'ele.me' WHERE row_num = 444 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.keep.com', apply_text = 'keep.com' WHERE row_num = 487 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.futunn.com', apply_text = 'futunn.com' WHERE row_num = 493 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.pharmaron.cn', apply_text = 'pharmaron.cn' WHERE row_num = 520 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.tigermed.net', apply_text = 'tigermed.net' WHERE row_num = 522 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.tongwei.com', apply_text = 'tongwei.com' WHERE row_num = 534 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.4paradigm.com', apply_text = '4paradigm.com' WHERE row_num = 569 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.pingcap.com', apply_text = 'pingcap.com' WHERE row_num = 572 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.weride.ai', apply_text = 'weride.ai' WHERE row_num = 577 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.luckincoffee.com', apply_text = 'luckincoffee.com' WHERE row_num = 593 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.empyrean.com.cn', apply_text = 'empyrean.com.cn' WHERE row_num = 595 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.didiglobal.com', apply_text = 'didiglobal.com' WHERE row_num = 612 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.haidilao.com', apply_text = 'haidilao.com' WHERE row_num = 647 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.bloomagebiotech.com', apply_text = 'bloomagebiotech.com' WHERE row_num = 704 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.piesat.cn', apply_text = 'piesat.cn' WHERE row_num = 728 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.feihe.com', apply_text = 'feihe.com' WHERE row_num = 750 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.yuewen.com', apply_text = 'yuewen.com' WHERE row_num = 769 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.oceanbase.com', apply_text = 'oceanbase.com' WHERE row_num = 771 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.zilliz.com', apply_text = 'zilliz.com' WHERE row_num = 775 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.dreame.com', apply_text = 'dreame.com' WHERE row_num = 786 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.yadea.com.cn', apply_text = 'yadea.com.cn' WHERE row_num = 791 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.tuya.com', apply_text = 'tuya.com' WHERE row_num = 814 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.ecovacs.com', apply_text = 'ecovacs.com' WHERE row_num = 817 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.roborock.com', apply_text = 'roborock.com' WHERE row_num = 818 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.laiye.com', apply_text = 'laiye.com' WHERE row_num = 819 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.innosilicon.com.cn', apply_text = 'innosilicon.com.cn' WHERE row_num = 828 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.picoxr.com', apply_text = 'picoxr.com' WHERE row_num = 838 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.empyrean.com.cn', apply_text = 'empyrean.com.cn' WHERE row_num = 850 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.mgi-tech.com', apply_text = 'mgi-tech.com' WHERE row_num = 853 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.qualcomm.cn', apply_text = 'qualcomm.cn' WHERE row_num = 873 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.bosch.com.cn', apply_text = 'bosch.com.cn' WHERE row_num = 876 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.astrazeneca.com.cn', apply_text = 'astrazeneca.com.cn' WHERE row_num = 881 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.meitu.com', apply_text = 'meitu.com' WHERE row_num = 910 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.smzdm.com', apply_text = 'smzdm.com' WHERE row_num = 918 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.cctc.cc', apply_text = 'cctc.cc' WHERE row_num = 952 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.hanslaser.com', apply_text = 'hanslaser.com' WHERE row_num = 960 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.freshhema.com', apply_text = 'freshhema.com' WHERE row_num = 976 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.pagoda.com.cn', apply_text = 'pagoda.com.cn' WHERE row_num = 977 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.samsung.com.cn', apply_text = 'samsung.com.cn' WHERE row_num = 1399 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.bosch.com.cn', apply_text = 'bosch.com.cn' WHERE row_num = 1404 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.honeywell.com.cn', apply_text = 'honeywell.com.cn' WHERE row_num = 1408 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.rtx.com', apply_text = 'rtx.com' WHERE row_num = 1409 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.boeing.com', apply_text = 'boeing.com' WHERE row_num = 1411 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.novartis.com.cn', apply_text = 'novartis.com.cn' WHERE row_num = 1416 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.lilly.com.cn', apply_text = 'lilly.com.cn' WHERE row_num = 1420 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.astrazeneca.com.cn', apply_text = 'astrazeneca.com.cn' WHERE row_num = 1421 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.mondelezinternational.com', apply_text = 'mondelezinternational.com' WHERE row_num = 1431 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.mcdonalds.com.cn', apply_text = 'mcdonalds.com.cn' WHERE row_num = 1437 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.yumchina.com', apply_text = 'yumchina.com' WHERE row_num = 1438 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.costco.com.cn', apply_text = 'costco.com.cn' WHERE row_num = 1440 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.accenture.cn', apply_text = 'accenture.cn' WHERE row_num = 1441 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.hsbc.com.cn', apply_text = 'hsbc.com.cn' WHERE row_num = 1446 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.goldmansachs.com', apply_text = 'goldmansachs.com' WHERE row_num = 1451 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.jpmorganchase.com', apply_text = 'jpmorganchase.com' WHERE row_num = 1452 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.bain.com', apply_text = 'bain.com' WHERE row_num = 1456 AND apply_url LIKE '%/careers%';
UPDATE companies SET apply_url = 'https://www.tesla.cn', apply_text = 'tesla.cn' WHERE row_num = 1457 AND apply_url LIKE '%/careers%';
